kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  labels:
    placement: pacman-placement-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
