apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-certificates
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: hub-placement
      requeueAfterSeconds: 30
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: cluster-certificates-{{name}}
    spec:
      destination:
        namespace: openshift-ingress
        server: '{{server}}'
      project: default
      source:
        path: cluster-certificates/{{name}}
        repoURL: https://github.com/kincl/acm-regional-dr-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
