--- 
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  enableCephTools: true
  manageNodes: false
  labelSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/storage, operator: Exists}
  monPVCTemplate: 
    spec: 
      accessModes: 
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 10Gi
      storageClassName: gp3-csi  #  <-- This should be changed as per platform
      volumeMode: Filesystem
  storageDeviceSets: 
    - count: 1
      dataPVCTemplate: 
        spec: 
          accessModes: 
            - ReadWriteOnce
          resources: 
            requests: 
              storage: 0.5Ti    # <--- Supported sizes are 0.5, 2, 4 Ti
          storageClassName: gp3-csi   #  <-- This should be changed as per platform
          volumeMode: Block
      name: ocs-deviceset
      placement: {}
      portable: true
      replica: 3
      resources: {}
