apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

configMapGenerator:
- name: haproxy-glb-config
  files:
  - haproxy.cfg
  options:
    disableNameSuffixHash: true
    labels:
      app: haproxy-glb

resources:
- service.yaml
- deployment.yaml
- route.yaml
