apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- target:
    kind: StorageCluster
    name: ocs-storagecluster
    namespace: openshift-storage
  patch: |-
    - op: add
      path: /spec/network
      value: {"multiClusterService": {"clusterID": "cluster-us", "enabled": true}}
