apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-secret-management
  namespace: openshift-gitops
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: local-cluster
      operator: NotIn
      values:
      - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-secret-management
  namespace: openshift-gitops
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-secret-management
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: secret-management
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secret-management
  namespace: openshift-gitops
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: secrets
      spec:
        object-templates:

        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: google-client-secret
              namespace: openshift-config
            data:
              clientSecret: (base64-encoded client secret from google)

        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec:
              identityProviders:
              - google:
                  clientID: (client id from google)
                  clientSecret:
                    name: google-client-secret
                  hostedDomain: redhat.com
                mappingMethod: claim
                name: google
                type: Google

        remediationAction: enforce
        severity: low