apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centos-test
  labels:
    app: centos-test
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: centos-source
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  volumeMode: Block
