apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centos-test
  labels:
    app: centos-test 
    placement: vm-placement-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  volumeMode: Filesystem
