apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-test
  labels:
    app: centos-test 
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: centos-stream9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: centos-test
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
        resources: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - persistentVolumeClaim:
          claimName: centos-test
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: centos
            password: centos
            chpasswd: { expire: False }
        name: cloudinitdisk
