apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-metadata
  labels:
    app: cloud-metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-metadata
  template:
    metadata:
      labels:
        app: cloud-metadata
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/python:latest
        command:
        - python3
        - /application/app.py
        name: python
        volumeMounts:
        - name: app
          mountPath: /application
      volumes:
      - name: app
        configMap:
          name: cloud-metadata
