apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: cloud-metadata
  files:
  - app.py
  options:
    disableNameSuffixHash: true
    labels:
      app: cloud-metadata

resources:
- service.yaml
- deployment.yaml
