apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-metadata
  name: cloud
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloud-metadata
  type: ClusterIP
