apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    email: jason@kincl.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-2
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key
