apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
- credentialsrequest.yaml
- clusterissuer-letsencrypt.yaml
- cert-manager.yaml